#include <cstdlib>
#include <memory>
#include <iostream>
#include "CommandLineOptions.hpp"
#include "DataProcessingEngine.hpp"
#include "AcquisitionManager.hpp"
#include "AdvantechDevice.hpp"
#include "BinaryFileWriter.hpp"
#include "Logger.hpp"